version: '3.8'
services:
  fastapi:
    container_name: fastapi-pokemon
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'

  postgres:
    container_name: pokemonDB
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=hard
      - POSTGRES_USER=main
      - POSTGRES_DB=pokemon
    volumes:
      - type: volume
        source: pokemondata
        target: /var/lib/postgresql/data

volumes:
  pokemondata: